CREATE TABLE "GCG_3992_BI_PICK_LST"(
 "BIRUNID" BIGINT,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "JOB_SEQ" CHAR(6),
 "PART" CHAR(20),
 "DESCRIPTION" CHAR(30),
 "QTY_ORDER" NUMERIC(12,4) DEFAULT '0',
 "QTY_STAGED" NUMERIC(12,4) DEFAULT '0',  "QTY_PICK" NUMERIC(12,4) DEFAULT '0',  "QTY_BINS" NUMERIC(12,4) DEFAULT '0',  "QTY_SHIPPED" NUMERIC(12,4) DEFAULT '0',  "DATE_DUE" DATE DEFAULT '1900-01-01',  "PROJECT" CHAR(7),  "PHASE" CHAR(4),  "BIN" CHAR(6));
