CREATE TABLE "GCG_3992_SHIP_LNS"(
 "PACK_LIST_NO" INTEGER,
 "PROJECT" CHAR(7),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "JOB_SEQ" CHAR(6),
 "PART" CHAR(20),
 "UM" CHAR(2),
 "DESCRIPTION" CHAR(30),
 "QTY_ORDER" NUMERIC(12,4),
 "QTY_BO" NUMERIC(12,4),
 "QTY_SHIPPED" NUMERIC(12,4),
 "BIN" CHAR(6));
